// ===== BASICS
// Get OpenID Connect Metadata
GET https://login.microsoftonline.com/rainertimecockpit.onmicrosoft.com/v2.0/.well-known/openid-configuration

// Get ID Token
GET https://login.microsoftonline.com/022e4faf-c745-475a-be06-06b1e1c9e39d/oauth2/v2.0/authorize?client_id=4cc39076-555a-48f5-bdb8-c9fc8134a35f&response_type=id_token&redirect_uri=https%3A%2F%2Flocalhost:5000%2Flogin&response_mode=form_post&scope=openid&state=12345&nonce=678910


// ===== CODE GRANT FLOW
// Get Code (Code Grant Flow)
GET https://rainerdemo.eu.auth0.com/authorize?client_id=wDEfs7qeFtB...&response_type=code&redirect_uri=https%3A%2F%2Flocalhost:5000%2Flogin&response_mode=query&scope=openid%20offline_access&state=12345

// Get Token from Code
POST https://rainerdemo.eu.auth0.com/oauth/token
Content-Type: application/x-www-form-urlencoded

client_id=wDEfs7qeFtB...&scope=openid%20offline_access&code=DtoirWzOBAxXXqGO&redirect_uri=https%3A%2F%2Flocalhost:5000%2Flogin&grant_type=authorization_code&client_secret=-oAiMEy...

// Get Code with Scope
GET https://rainerdemo.eu.auth0.com/authorize?client_id=wDEfs7qeFtB...&response_type=code&redirect_uri=https%3A%2F%2Flocalhost:5000%2Flogin&response_mode=query&audience=http%3A%2F%2Foidc-webapi%2F&scope=openid%20offline_access%20read:data&state=12345

// Get Token from Code
POST https://rainerdemo.eu.auth0.com/oauth/token
Content-Type: application/x-www-form-urlencoded

client_id=wDEfs7qeFtB...&audience=http%3A%2F%2Foidc-webapi%2F&scope=openid%20offline_access%20read:data&code=X6A7HzN7aPKZPF-6&redirect_uri=https%3A%2F%2Flocalhost:5000%2Flogin&grant_type=authorization_code&client_secret=-oAiMEy...

// Try access token in C# Web API
GET http://localhost:5000/api/values
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZC...


// ===== IMPLICIT FLOW
// Get Code with Scope
GET https://rainerdemo.eu.auth0.com/authorize?client_id=wDEfs7qeFtB...&response_type=token&redirect_uri=https%3A%2F%2Flocalhost:5000%2Flogin&response_mode=fragment&audience=http%3A%2F%2Foidc-webapi%2F&scope=openid%20offline_access%20read:data&state=12345

// Try access token in Node.js Web API
GET http://localhost:5001/api/values
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIs...


// ===== HYBRID FLOW
// Get Code with Scope
GET https://rainerdemo.eu.auth0.com/authorize?client_id=wDEfs7qeFtB...&response_type=code%20id_token&redirect_uri=https%3A%2F%2Flocalhost:5000%2Flogin&response_mode=form_post&audience=http%3A%2F%2Foidc-webapi%2F&scope=openid%20email%20offline_access%20read:data&state=12345&nonce=67890


// ===== CLIENT CREDENTIALS
// Get Tokens
POST https://rainerdemo.eu.auth0.com/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&audience=http%3A%2F%2Foidc-webapi%2F&client_id=wDEfs7qeFtB...&client_secret=-oAiMEy...

