#@host=http://localhost:5000
@host=https://app-owsag5bbmhyzi.azurewebsites.net/
#@backend=http://localhost:7071
@backend=https://func-owsag5bbmhyzi.azurewebsites.net

###
GET {{host}}/ping

###
// @name copy
POST {{host}}/copy-file
    ?uri=https://linz.coderdojo.net/images/loeten_hu003f52725c3db9114af2e90dc9efff82_339641_1920x1200_fit_q75_box.jpg
    &name=coderdojo.jpg
Content-Type: application/json

###
GET {{copy.response.headers.location}}

###
POST {{host}}/keep-secret?name=mySecret&value=P@ssw0rd!123

###
GET {{host}}/get-secret?name=mySecret

###
GET {{host}}/from-db

###
GET {{backend}}/api/ping

###
GET {{backend}}/api/secureping
Authorization: Bearer eyJ0eXAiOiJKV1QiL...

###
GET {{host}}/ping-backend

###
GET {{host}}/backend-token

###
GET {{host}}/secure-ping-backend
