GET https://msi-basta-vault-live.vault.azure.net/secrets/API-Key?api-version=2016-10-01
Authorization: Bearer eyJ0eXAiOiJKV...
Content-Type: application/json
Accept: application/json

###
GET https://login.microsoftonline.com/rainertimecockpit.onmicrosoft.com/.well-known/openid-configuration
