/**
 * @fileoverview gRPC-Web generated client stub for Demo
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: greet.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as greet_pb from './greet_pb'; // proto import: "greet.proto"


export class GreeterClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSayHello = new grpcWeb.MethodDescriptor(
    '/Demo.Greeter/SayHello',
    grpcWeb.MethodType.UNARY,
    greet_pb.HelloRequest,
    greet_pb.HelloReply,
    (request: greet_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    greet_pb.HelloReply.deserializeBinary
  );

  sayHello(
    request: greet_pb.HelloRequest,
    metadata?: grpcWeb.Metadata | null): Promise<greet_pb.HelloReply>;

  sayHello(
    request: greet_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: greet_pb.HelloReply) => void): grpcWeb.ClientReadableStream<greet_pb.HelloReply>;

  sayHello(
    request: greet_pb.HelloRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: greet_pb.HelloReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Demo.Greeter/SayHello',
        request,
        metadata || {},
        this.methodDescriptorSayHello,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Demo.Greeter/SayHello',
    request,
    metadata || {},
    this.methodDescriptorSayHello);
  }

}

export class MathGuruClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetFibonacci = new grpcWeb.MethodDescriptor(
    '/Demo.MathGuru/GetFibonacci',
    grpcWeb.MethodType.SERVER_STREAMING,
    greet_pb.FromTo,
    greet_pb.NumericResult,
    (request: greet_pb.FromTo) => {
      return request.serializeBinary();
    },
    greet_pb.NumericResult.deserializeBinary
  );

  getFibonacci(
    request: greet_pb.FromTo,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<greet_pb.NumericResult> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/Demo.MathGuru/GetFibonacci',
      request,
      metadata || {},
      this.methodDescriptorGetFibonacci);
  }

}

