@host = http://dev-01:5000

###
# @name CreateCampaign
POST {{host}}/campaigns
Accept: application/json
Content-Type: application/json

{
    "name": "Test Campaign",
    "organizer": "Test Organizer",
    "reservedRatioForGirls": -1,
    "dates": [
        {
            "date": "2025-06-01",
            "startTime": "10:00",
            "endTime": "13:00",
            "departmentAssignments": [
                {
                    "departmentName": "Informatik",
                    "numberOfSeats": 10
                }
            ]
        }
    ]
}