POST https://oai-4.openai.azure.com/openai/deployments/complete-35-16k/chat/completions?api-version=2023-05-15
Content-Type: application/json
api-key: 8745099a2642431380a2374ab4d24867

{
    "messages": [
        {
            "role": "system", 
            "content": "You are a helpful assistant."
        },
        {
            "role": "user", 
            "content": "Does Azure OpenAI support customer managed keys?"
        },
        {
            "role": "assistant", 
            "content": "Yes, customer managed keys are supported by Azure OpenAI."
        },
        {
            "role": "user", 
            "content": "Do other Azure AI services support this too?"
        }
    ]
}