@baseAddress = http://localhost:7071

###
# @name speedViolation1
# Description of the responses see also
# https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api
POST {{baseAddress}}/api/SpeedViolationRecognition
Content-Type: application/json

{
    "CameraID": 42,
    "LicensePlateNumber": "XY-0815",
    "RecognitionAccuracy": 0.6,
    "SpeedKmh": 90
}

###
# @name statusQuery
GET {{speedViolation1.response.body.$.statusQueryGetUri}}


###
@orchId = {{speedViolation1.response.body.id}}

POST {{baseAddress}}/api/ProcessSlackApproval
Content-Type: application/json

{
    "OrchestrationInstanceID": "{{orchId}}",
    "Approved": true
}

###
GET {{baseAddress}}/api/lawsuite/{{statusQuery.response.body.$.customStatus}}
Accept: application/json

###
POST {{baseAddress}}/api/lawsuite/{{statusQuery.response.body.$.customStatus}}/setDriver
Content-Type: application/json

"Foo Bar"
