@host = https://svrlstictactoe.azurewebsites.net
@localhost = http://localhost:7071

###
POST {{ host }}/api/TicTacToe
Content-Type: application/json

[ " ", "X", " ",
  " ", "X", " ",
  " ", "X", " " ]

###
POST {{ host }}/api/TicTacToe
Content-Type: application/json

[ " ", "X", " " ]

###
GET {{ localhost }}/api/SayHello?name=Tom

###
POST http://localhost:7071/api/generate-demo-data

###
POST https://srvlstrafficmonitor.azurewebsites.net/api/generate-demo-data

###
POST https://62d61df3.ngrok.io/api/slackapproval
